config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'
  root 'pages#index'
  get 'pages/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :detail, presence: :true
    validates :price, numericality: { greater_than: 1, less_than: 1001 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @tasks = Task.all
  end

  def create
    # byebug
    @task = Task.create(detail: params[:detail], price: params[:price].to_i)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/create.html.erb
<% if @task.errors.any? %>
 <div id="error_explanation">
    <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being
    saved:</h2>
    <ul>
        <% @task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
 </div>
<% else %>
 <h1>Exito !!!! </h1>
 <%= link_to 'Home', root_path  %>
<% end %>

app/views/pages/index.html.erb
<form action="<%= pages_create_path  %>" class="container">
  <div class="form-group">
    <label for="detail">Detail</label>
    <input name="detail" type="text" class="form-control" id="detail" aria-describedby="emailHelp" required>
  </div>
  <div class="form-group">
    <label for="price">Price</label>
    <input name="price" type="number" class="form-control" id="price">
  </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
</form>


<ul>
    <%  @tasks.each do |task| %>
        <li><%=  task.detail %></li>
    <% end %>
</ul>

app/views/shared/_nav.html.erb
<nav>
    <%= link_to "Home", root_path %>
    <%= link_to "Task" , tasks_index_path %>
</nav>

app/views/tasks/index.html.erb
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Detail</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <%  @tasks.each do |task| %>
            <tr>
                <td><%= task.id %></td>
                <td><%= task.detail %></td>
                <td><%= task.price %></td>
            </tr>
        <% end %>
    </table>
</div>